version: '3.8'

services:
  mongo:
    image: 'mongo'
    restart: always
    hostname: 'mongo-server'
    container_name: my-mongo-container
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      # MONGO_INITDB_DATABASE: appdb
  app:
    build: .
    container_name: my-app-container
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mongo

volumes:
  mongo-data:
